### ISSUE TITLE
Bad Links

### ISSUE THREAD

**Issue by justinmoon** [wbobeirne/joule-splash#2]
GitHub link in the footer of https://lightningjoule.com/ points to https://github.com/wbobeirne. https://github.com/wbobeirne/joule-extension/ would be better IMO

The twitter link on https://lightningjoule.com/contact says @WBOBEIRN but points to @lightningjoule

Originally filed in https://github.com/wbobeirne/joule-extension/issues/155

**Comment by wbobeirne** [comment]
Thanks for catching Justin! Sorry I didn't see this issue before, gonna have it licked this afternoon.

**Comment by wbobeirne** [comment]
Closed via 827083f
